
The RV_sa-hn-ru-de-en.html file is from Marcis Gasuns. June, 2018
* RV_sa-hn-ru-de-en_1.html (remove one bad character)
There is a bad character in the file at the last verse.
After correcting this (to double-danda), the result is
RV_sa-hn-ru-de-en_1.html.  Note: this is done in Emacs.  Could not
write a Python program to do this??

Failed attempt to do this with Python code -- no luck
python rvtest.py 2 RV_sa-hn-ru-de-en.html  RV_sa-hn-ru-de-en_1.html 
There is a problem in displaying accent + visarga.



* python rvtest.py 0 badchars.txt badchars_examine.txt

* redo.sh
creates several intermediate files from RV_sa-hn-ru-de-en_1.html
Then
 recreates rvhymns.
Then deletes intermediate files
* clean.sh
 removes intermediate files
* --------------------------------------------------
*  work
* display with special font, using 'ee8083'
The file codes this in a special way, using accent + 'ee8083'.
This displays properly when using the siddhanta or sanskrit2003 font;
see 'RV_orig_sanskrit2003.html' or RV_orig_siddhanta.html  (which
contain just through 1.003.xxx).
* RV_sa-hn-ru-de-en_2.html   No
The RV_sa-hn-ru-de-en_2.html changes the spellings from
 'accent + ee8083' to 'accent + visarga'.
It does not display properly whatever the font.

* RV_sa-hn-ru-de-en_3.html
The Sanskrit Documents version of rig veda changes the spelling 
from 'vowel + accent + visarga' to 'vowel + visarga + accent'.
This spelling may be inaccurate (see note), but it displays almost properly
 (the accent positioning is changed to be over the : of visarga).
The RV_sa-hn-ru-de-en_3.html file changes the spellings from
  'vowel + accent + ee8083' to 'vowel + visarga + accent'.

 NOTE: according to SergeA, 'vowel + visarga + accent' is correct spelling.

python rvtest.py 5 RV_sa-hn-ru-de-en_1.html RV_sa-hn-ru-de-en_3a.html

* RV_sa-hn-ru-de-en_4.html
python rvtest.py 6 RV_sa-hn-ru-de-en_3a.html RV_sa-hn-ru-de-en_4a.html

 ascii digit 1 or 3 followed by 57353 + 57351 (two special editing characters,
 probably for sanskrit2003 font)
 Change to devanagari digit one or three + udatta + anudatta.
 664 changes in 651 lines.
 This is now comparable to the Sanskrit Documents version of Rg Veda:
   https://sanskritdocuments.org/doc_veda/r01.html?lang=sa
This is created from RV_...3.html by function temp6() in rvtest.py

* RV_sa-hn-ru-de-en_5.html
Use unix line-endings
python rvtest.py 7 RV_sa-hn-ru-de-en_4.html RV_sa-hn-ru-de-en_5.html


* rvhymns
  Hymns are named rv01.001 
  A particular verse rv01.001.01
  files named rv01.001.html
mkdir rvhymns
python make_hymns_01.py RV_sa-hn-ru-de-en_5.html rvhymns

118535 lines
10552 verses found
1028 hymns found

